import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

/// The review sheet is generated by `tool/review_sheet.dart`, and generated
/// files drift: this one silently fell twenty claims behind the content while
/// the malpractice module and three checklists were added, so the README went
/// on reporting a review backlog smaller than the real one.
///
/// Counting the same claims here means the sheet cannot go stale unnoticed
/// again. When this fails, the fix is to re-run the generator, not to edit the
/// numbers.
void main() {
  int countClaims({required bool onlyPending}) {
    var n = 0;

    void walk(List<dynamic>? citations) {
      for (final c in citations ?? const []) {
        final status = ((c as Map)['status'] as String?) ?? 'review';
        if (!onlyPending || status != 'verified') n++;
      }
    }

    final guideIndex = jsonDecode(
        File('assets/content/guide/index.json').readAsStringSync()) as Map;
    for (final f in guideIndex['modules'] as List) {
      final mod = jsonDecode(File('assets/content/guide/modules/$f')
          .readAsStringSync()) as Map;
      for (final card in mod['cards'] as List) {
        walk((card as Map)['citations'] as List<dynamic>?);
      }
    }

    final index = jsonDecode(File('assets/content/checklists/index.json')
        .readAsStringSync()) as Map;
    for (final f in index['packs'] as List) {
      final pack = jsonDecode(
          File('assets/content/checklists/$f').readAsStringSync()) as Map;
      for (final stage in pack['stages'] as List) {
        for (final item in (stage as Map)['items'] as List) {
          walk((item as Map)['citations'] as List<dynamic>?);
        }
      }
    }

    final prices = jsonDecode(
        File('assets/content/rates/prices.json').readAsStringSync()) as Map;
    // Prices name the field 'sources', not 'citations'.
    for (final m in prices['materials'] as List) {
      walk((m as Map)['sources'] as List<dynamic>?);
    }
    for (final b in prices['benchmarks'] as List) {
      walk((b as Map)['sources'] as List<dynamic>?);
    }
    return n;
  }

  test('the generated review sheet still matches the content', () {
    final sheet = File('docs/CONTENT_REVIEW.md').readAsStringSync();
    int stated(String label) {
      final m = RegExp('$label: \\*\\*(\\d+)\\*\\*').firstMatch(sheet);
      expect(m, isNotNull, reason: 'could not read "$label" from the sheet');
      return int.parse(m!.group(1)!);
    }

    expect(stated('Claims with a citation'), countClaims(onlyPending: false),
        reason: 'run: dart run tool/review_sheet.dart');
    expect(stated('Awaiting engineer sign-off'), countClaims(onlyPending: true),
        reason: 'run: dart run tool/review_sheet.dart');
  });

  test('the README reports the same backlog the sheet does', () {
    final sheet = File('docs/CONTENT_REVIEW.md').readAsStringSync();
    final readme = File('README.md').readAsStringSync();
    for (final label in ['Claims with a citation', 'Awaiting engineer sign-off']) {
      final n = RegExp('$label: \\*\\*(\\d+)\\*\\*').firstMatch(sheet)!.group(1)!;
      expect(readme, contains(n),
          reason: 'README does not mention $label = $n');
    }
  });
}
