// Regenerates docs/CONTENT_REVIEW.md from the shipped content packs.
//
// Run: dart run tool/review_sheet.dart
//
// The sheet is generated rather than hand-kept so it cannot drift away from
// what the app actually shows. Every technical claim in the app appears here
// with its source and its review state; a reviewing engineer works down this
// file and flips `status` to "verified" in the JSON as each one is checked.
import 'dart:convert';
import 'dart:io';

void main() {
  final rows = <List<String>>[];

  void walkCitations(String where, List<dynamic>? citations) {
    for (final c in citations ?? const []) {
      final m = c as Map<String, dynamic>;
      rows.add([
        where,
        (m['source'] as Map)['bn'] as String,
        m['clause'] == null ? '' : (m['clause'] as Map)['bn'] as String,
        (m['status'] as String?) ?? 'review',
      ]);
    }
  }

  final guide = jsonDecode(
      File('assets/content/guide/guide.json').readAsStringSync()) as Map;
  for (final mod in guide['modules'] as List) {
    for (final card in mod['cards'] as List) {
      walkCitations('${mod['code']} · ${card['id']}',
          card['citations'] as List<dynamic>?);
    }
  }

  final index = jsonDecode(
      File('assets/content/checklists/index.json').readAsStringSync()) as Map;
  for (final f in index['packs'] as List) {
    final pack = jsonDecode(
        File('assets/content/checklists/$f').readAsStringSync()) as Map;
    for (final stage in pack['stages'] as List) {
      for (final item in stage['items'] as List) {
        walkCitations('${pack['id']} · ${item['id']}',
            item['citations'] as List<dynamic>?);
      }
    }
  }

  final prices = jsonDecode(
      File('assets/content/rates/prices.json').readAsStringSync()) as Map;
  for (final m in prices['materials'] as List) {
    walkCitations('price · ${m['id']} (as of ${m['as_of']})',
        m['sources'] as List<dynamic>?);
  }
  for (final b in prices['benchmarks'] as List) {
    walkCitations(
        'benchmark · ${b['id']} (year ${b['year'] ?? 'unconfirmed'})',
        b['sources'] as List<dynamic>?);
  }

  final pending = rows.where((r) => r[3] != 'verified').length;
  final out = StringBuffer()
    ..writeln('# Content review sheet')
    ..writeln()
    ..writeln('Generated by `dart run tool/review_sheet.dart`. Do not edit by '
        'hand — change the `status` field in the content JSON instead.')
    ..writeln()
    ..writeln('- Claims with a citation: **${rows.length}**')
    ..writeln('- Awaiting engineer sign-off: **$pending**')
    ..writeln()
    ..writeln('A claim moves to `verified` only when a licensed civil engineer '
        '(or, for the rights modules, someone who has actually filed RTI '
        'applications in Bangladesh) has checked it against the cited source '
        'and initialled the row. Until then the app shows an amber '
        '"ইঞ্জিনিয়ার যাচাই বাকি" badge on it.')
    ..writeln()
    ..writeln('| Where | Source | Clause | Status | Reviewer | Date |')
    ..writeln('|---|---|---|---|---|---|');
  for (final r in rows) {
    out.writeln('| ${r[0]} | ${r[1]} | ${r[2]} | ${r[3]} | | |');
  }

  Directory('docs').createSync(recursive: true);
  File('docs/CONTENT_REVIEW.md').writeAsStringSync(out.toString());
  stdout.writeln(
      'docs/CONTENT_REVIEW.md: ${rows.length} claims, $pending awaiting review');
}
